// =============================================================================
// Git Hook Installation
// =============================================================================
//
// `convit hook install` writes a `prepare-commit-msg` hook that calls
// `convit hook run` to populate the commit-msg file with a generated message.
// `convit hook uninstall` removes it. The generation itself runs in `runHook`
// (src/cli/index.ts); this module only manages the hook file on disk.
// =============================================================================

import { execFileSync } from "child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "fs";
import { join } from "path";
import { pc } from "./ui";

/** Marker line identifying a convit-managed hook (idempotent install/uninstall). */
export const CONVIT_HOOK_MARKER = "convit-managed-hook";

const HOOK_NAME = "prepare-commit-msg";
const BACKUP_SUFFIX = ".convit-bak";

/**
 * POSIX-sh `prepare-commit-msg` body. Pinned to LF endings: a CRLF shebang
 * (`#!/bin/sh\r`) breaks hook execution, and this repo converts LF→CRLF on write,
 * so the bytes are assembled here and written verbatim with `utf-8` (no editor
 * normalization). Tries `convit` on PATH, then `npx`, and fails open — if convit
 * is unavailable or errors, the message is left untouched and the commit proceeds.
 */
export function hookScriptContent(): string {
  return [
    "#!/bin/sh",
    `# ${CONVIT_HOOK_MARKER}`,
    "# Populates the commit message with a Conventional Commit generated by convit.",
    "# Fails open: any error leaves the message untouched so the commit proceeds.",
    "if command -v convit >/dev/null 2>&1; then",
    '  convit hook run "$1" "$2" "$3" || true',
    "elif command -v npx >/dev/null 2>&1; then",
    '  npx --no-install convit hook run "$1" "$2" "$3" 2>/dev/null || true',
    "fi",
    "",
  ].join("\n");
}

/** True when the file at `path` exists and is a convit-managed hook. */
export function isConvitHook(path: string): boolean {
  try {
    return readFileSync(path, "utf-8").includes(CONVIT_HOOK_MARKER);
  } catch {
    return false;
  }
}

/** Resolves the repo's git hooks dir (respects core.hooksPath / worktrees). */
function hooksDir(): string {
  return execFileSync("git", ["rev-parse", "--git-path", "hooks"], {
    encoding: "utf-8",
  }).trim();
}

export function installHook(): void {
  let dir: string;
  try {
    dir = hooksDir();
  } catch {
    console.error(
      pc.red("Not a git repository — run `convit hook install` inside one."),
    );
    process.exit(1);
  }
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const hookPath = join(dir, HOOK_NAME);

  // A foreign (non-convit) hook is present — preserve it before overwriting.
  if (existsSync(hookPath) && !isConvitHook(hookPath)) {
    const backup = hookPath + BACKUP_SUFFIX;
    if (existsSync(backup)) {
      console.error(
        pc.red(
          `A foreign ${HOOK_NAME} hook and a backup already exist.\n` +
            `  Resolve ${backup} manually, then re-run.`,
        ),
      );
      process.exit(1);
    }
    renameSync(hookPath, backup);
    console.log(
      pc.yellow(`Backed up existing ${HOOK_NAME} → ${HOOK_NAME}${BACKUP_SUFFIX}`),
    );
  }

  const updating = isConvitHook(hookPath);
  writeFileSync(hookPath, hookScriptContent(), "utf-8");
  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // chmod is a no-op on some Windows filesystems; git runs the hook regardless.
  }

  console.log(
    pc.green(`${updating ? "Updated" : "Installed"} convit ${HOOK_NAME} hook`) +
      pc.dim(
        `\n  ${hookPath}` +
          "\n  Runs on `git commit` (without -m). Needs `convit` resolvable on PATH.",
      ),
  );
}

export function uninstallHook(): void {
  let dir: string;
  try {
    dir = hooksDir();
  } catch {
    console.error(pc.red("Not a git repository."));
    process.exit(1);
  }
  const hookPath = join(dir, HOOK_NAME);

  if (!existsSync(hookPath)) {
    console.log(pc.dim(`No ${HOOK_NAME} hook to remove.`));
    return;
  }
  if (!isConvitHook(hookPath)) {
    console.error(
      pc.yellow(`${HOOK_NAME} is not convit-managed — leaving it untouched.`),
    );
    process.exit(1);
  }

  const backup = hookPath + BACKUP_SUFFIX;
  rmSync(hookPath);
  if (existsSync(backup)) {
    renameSync(backup, hookPath);
    console.log(
      pc.green(`Removed convit hook and restored the previous ${HOOK_NAME}.`),
    );
  } else {
    console.log(pc.green(`Removed convit ${HOOK_NAME} hook.`));
  }
}
